- hosts: all
  tasks:
    - name: add an host w/ clapi_host
      clapi_host: 
        username: "{{ centreon_clapi_username }}"
        password: "{{ centreon_clapi_password }}"
        hostname: "{{ inventory_hostname }}"
        ipaddress: "{{ ansible_default_ipv4.address }}"
        groupname: OS_Linux
        action: add
      delegate_to: "{{centreon_server}}"
      notify: "notify poller after modification"

    - name: remove host w/ clapi_host
      clapi_host:
        username: "{{ centreon_clapi_username }}"
        password: "{{ centreon_clapi_password }}"
        hostname: "{{ inventory_hostname }}"
        ipaddress: "{{ ansible_default_ipv4.address }}"
        action: delete
      delegate_to: "{{centreon_server}}"
      notify: "notify poller after modification"

    - name: remove another time host w/ clapi_host
      clapi_host:
        username: "{{ centreon_clapi_username }}"
        password: "{{ centreon_clapi_password }}"
        hostname: "{{ inventory_hostname }}"
        ipaddress: "{{ ansible_default_ipv4.address }}"
        action: delete
      delegate_to: "{{centreon_server}}"
      notify: "notify poller after modification"

    - name: add another time host w/ clapi_host
      clapi_host:
        username: "{{ centreon_clapi_username }}"
        password: "{{ centreon_clapi_password }}"
        hostname: "{{ inventory_hostname }}"
        ipaddress: "{{ ansible_default_ipv4.address }}"
        groupname: OS_Linux
        action: add
      delegate_to: "{{centreon_server}}"
      notify: "notify poller after modification"

    - name: delete hostgroup testgroup
      clapi_hostgroup:
        username: '{{ centreon_clapi_username }}'
        password: '{{ centreon_clapi_password }}'
        hostgroupname: testgroup
        action: delete
      delegate_to: '{{ centreon_server }}'
      notify: "notify poller after modification"

    - name: add testgroup hostgroup
      clapi_hostgroup:
        username: '{{ centreon_clapi_username }}'
        password: '{{ centreon_clapi_password }}'
        hostgroupname: testgroup
        hostgroupalias: "my test group"
        action: add
      delegate_to: '{{ centreon_server }}'
      notify: "notify poller after modification"

    - name: add testgroup hostgroup once again
      clapi_hostgroup:
        username: '{{ centreon_clapi_username }}'
        password: '{{ centreon_clapi_password }}'
        hostgroupname: testgroup
        hostgroupalias: "my test group"
        action: add
      delegate_to: '{{ centreon_server }}'
      notify: "notify poller after modification"

    - name: add host to OS_Linux hostgroup
      clapi_hostgroup:
        username: '{{ centreon_clapi_username }}'
        password: '{{ centreon_clapi_password }}'
        hostgroupname: testgroup
        members: '{{ inventory_hostname }}'
        action: addmembers
      delegate_to: '{{ centreon_server }}'
      notify: "notify poller after modification"

    - name: add host to OS_Linux hostgroup another time
      clapi_hostgroup:
        username: '{{ centreon_clapi_username }}'
        password: '{{ centreon_clapi_password }}'
        hostgroupname: testgroup
        members: '{{ inventory_hostname }}'
        action: addmembers
      delegate_to: '{{ centreon_server }}'
      notify: "notify poller after modification"

    - name: add generic-host template
      clapi_host:
        username: '{{ centreon_clapi_username }}'
        password: '{{ centreon_clapi_password }}'
        hostname: '{{ inventory_hostname }}'
        hosttemplate: "generic-host"
        action: addtemplate
      delegate_to: '{{ centreon_server }}'
      notify:
        - "notify poller after modification"
        - "apply template services to host"

  handlers:
    - name: apply template services to host
      clapi_host:
        username: '{{ centreon_clapi_username }}'
        password: '{{ centreon_clapi_password }}'
        hostname: '{{ inventory_hostname }}'
        action: applytpl
      delegate_to: '{{ centreon_server }}'

    - name: notify poller after modification
      clapi_poller:
        username: '{{ centreon_clapi_username }}'
        password: '{{ centreon_clapi_password }}'
        pollername: '{{ centreon_pollername }}'
      run_once: true
      delegate_to: '{{ centreon_server }}'
